export const descripcionesInsignias = [
    "Completó la Introducción ¡Has dado el primer paso! Introducción completada con éxito.",
    "Completó la Introducción al 100% ¡Perfección! No te faltó ni un solo detalle de la introducción.",
    "Completó el Módulo 1 ¡Buen trabajo! Has terminado el primer módulo del curso.",
    "Completó el Módulo 2 ¡Sigues avanzando! Módulo 2 superado.",
    "Completó el Módulo 3 ¡Increíble! Módulo 3 completado con éxito.",
    "Completó todos los módulos ¡Eres imparable! Finalizaste todos los módulos disponibles.",
    "Completó todos los módulos al 100% ¡Dominaste cada parte! Todos los módulos completados al máximo.",
    "Completó su primer curso ¡Felicidades! Has terminado tu primer curso completo.",
    "Completó 3 cursos ¡Triple logro! Ya completaste tres cursos.",
    "Finalizó todos los cursos disponibles ¡Maestría desbloqueada! Completaste todos los cursos del sistema.",
    "Obtuvo su certificado ¡Reconocimiento merecido! Ya tienes tu certificado oficial.", 
    "Inició sesión por primera vez ¡Bienvenido! Esta es tu primera vez dentro.", 
    "Personalizó su perfil ¡Le diste tu toque personal a tu perfil!", 
    "Ingresó al perfil ¡Curioso/a! Visitaste tu perfil por primera vez.",
    "Cambió su avatar ¡Nueva imagen, nueva actitud! Cambiaste tu avatar.", 
    "Cambió su apodo/nombre de usuario ¡Un nuevo nombre para nuevas aventuras!", 
    "Vio su primer video de clase ¡Comenzaste tu camino visual! Primer video visto.", 
    "Completó su primer ejercicio ¡Tu primer ejercicio completo! Bien hecho.", 
    "Realizó su primera evaluación ¡Hora de demostrar lo aprendido! Primera evaluación realizada.",
    "Completó un módulo en un solo día ¡Velocidad y dedicación! Terminaste un módulo en tiempo récord.", 
    "Realizó 10 ejercicios ¡Ya llevas 10 ejercicios! Sigue así.", 
    "Realizó 50 ejercicios ¡50 ejercicios completados! Eso es compromiso.", 
    "Contestó correctamente 5 evaluaciones ¡Cinco aciertos! Tus conocimientos rinden frutos.",
    "Sacó 100% en una evaluación ¡Perfecto! Acierto total en una evaluación.", 
    "Sacó 100% en 3 evaluaciones ¡Triple perfección! Tres evaluaciones con puntaje perfecto.", 
    "Respondió todas las preguntas de un módulo correctamente ¡Dominio total! No fallaste ni una en el módulo.", 
    "Mejoró su puntuación en una re-evaluación ¡Aprendiste de tus errores! Subiste tu nota.", 
    "Alcanzó el puntaje máximo en un minijuego ¡Campeón del juego! Lograste la puntuación máxima.",
    "Descubrió un secreto escondido ¡Explorador experto! Encontraste un secreto oculto.", 
    "Leyó todas las explicaciones de un módulo ¡Eres detallista! Leíste todo antes de continuar.", 
    "Usó pistas para aprender mejor ¡Aprender también es saber pedir ayuda!", 
    "Terminó un módulo sin usar ninguna pista ¡Sin ayuda! Completaste un módulo por tu cuenta.", 
    "Jugó un minijuego por primera vez ¡La diversión comienza! Jugaste tu primer minijuego.",
    "¡Personalizó su perfil! Le diste tu toque personal a tu perfil",
    "Descubrió un secreto escondido ¡Explorador experto! Encontraste un secreto oculto."
];